require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/database');
const Book = require('../models/Book');

const seedBooks = [
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    description: 'A Handbook of Agile Software Craftsmanship - Learn how to write code that is clean, readable, and maintainable.',
    category: 'Programming',
    price: 45.99,
    discountedPrice: 35.99,
    rating: 4.8,
    coverImage: 'https://covers.openlibrary.org/b/id/7899866-M.jpg',
    pages: 464,
    publicationDate: new Date('2008-08-01'),
    isbn: '978-0132350884',
    language: 'English',
    format: 'eBook',
    stock: 100,
    isFeatured: true,
    isTrending: true,
    tags: ['programming', 'coding', 'best-practices'],
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt, David Thomas',
    description: 'Your Journey to Mastery - Build your programming skills one step at a time.',
    category: 'Programming',
    price: 49.99,
    discountedPrice: 39.99,
    rating: 4.7,
    coverImage: 'https://covers.openlibrary.org/b/id/7933675-M.jpg',
    pages: 352,
    publicationDate: new Date('1999-10-30'),
    isbn: '978-0135957059',
    language: 'English',
    format: 'eBook',
    stock: 80,
    isFeatured: true,
    tags: ['programming', 'professional'],
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    description: 'Explore the two systems that drive the way you think and understand cognitive biases.',
    category: 'Psychology',
    price: 42.00,
    discountedPrice: 32.00,
    rating: 4.6,
    coverImage: 'https://covers.openlibrary.org/b/id/7933675-M.jpg',
    pages: 499,
    publicationDate: new Date('2011-10-25'),
    isbn: '978-0374275631',
    language: 'English',
    format: 'eBook',
    stock: 60,
    isTrending: true,
    tags: ['psychology', 'decision-making', 'cognitive-bias'],
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'An Easy & Proven Way to Build Good Habits and Break Bad Ones.',
    category: 'Self-Development',
    price: 38.00,
    discountedPrice: 28.00,
    rating: 4.9,
    coverImage: 'https://covers.openlibrary.org/b/id/8441350-M.jpg',
    pages: 320,
    publicationDate: new Date('2018-10-16'),
    isbn: '978-0735211292',
    language: 'English',
    format: 'eBook',
    stock: 150,
    isFeatured: true,
    isTrending: true,
    tags: ['self-help', 'habits', 'productivity'],
  },
  {
    title: 'The Art of Computer Programming',
    author: 'Donald E. Knuth',
    description: 'The definitive work on fundamental algorithms and data structures.',
    category: 'Programming',
    price: 89.99,
    discountedPrice: 69.99,
    rating: 4.9,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 800,
    publicationDate: new Date('1968-07-01'),
    isbn: '978-0321751041',
    language: 'English',
    format: 'eBook',
    stock: 40,
    isFeatured: true,
    tags: ['algorithms', 'programming', 'classic'],
  },
  {
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    description: 'Powerful Lessons in Personal Change - Transform your life with these timeless habits.',
    category: 'Self-Development',
    price: 35.00,
    discountedPrice: 25.00,
    rating: 4.5,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 400,
    publicationDate: new Date('1989-08-15'),
    isbn: '978-0743269513',
    language: 'English',
    format: 'eBook',
    stock: 90,
    isTrending: true,
    tags: ['self-help', 'leadership', 'effectiveness'],
  },
  {
    title: 'Good to Great',
    author: 'Jim Collins',
    description: 'Why Some Companies Make the Leap and Others Don\'t - Business excellence explained.',
    category: 'Business',
    price: 44.00,
    discountedPrice: 34.00,
    rating: 4.7,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 300,
    publicationDate: new Date('2001-10-01'),
    isbn: '978-0066620992',
    language: 'English',
    format: 'eBook',
    stock: 75,
    isFeatured: true,
    tags: ['business', 'leadership', 'management'],
  },
  {
    title: 'The Innovators',
    author: 'Walter Isaacson',
    description: 'How a Group of Hackers, Geniuses, and Geeks Created the Digital Revolution.',
    category: 'Programming',
    price: 48.00,
    discountedPrice: 38.00,
    rating: 4.6,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 542,
    publicationDate: new Date('2014-10-07'),
    isbn: '978-1476708690',
    language: 'English',
    format: 'eBook',
    stock: 55,
    tags: ['technology', 'history', 'innovation'],
  },
  {
    title: 'Cryptography Basics',
    author: 'Steve Burnett, Stephen Paine',
    description: 'A Practical Introduction to Modern Cryptography for Secure Communication.',
    category: 'Cybersecurity',
    price: 55.00,
    discountedPrice: 45.00,
    rating: 4.4,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 415,
    publicationDate: new Date('2001-08-01'),
    isbn: '978-0471117094',
    language: 'English',
    format: 'eBook',
    stock: 45,
    isFeatured: true,
    tags: ['cybersecurity', 'cryptography', 'security'],
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'A fantasy adventure that launched an epic saga. Join Bilbo on his unexpected journey.',
    category: 'Fiction',
    price: 25.00,
    discountedPrice: 18.00,
    rating: 4.8,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 310,
    publicationDate: new Date('1937-09-21'),
    isbn: '978-0547928227',
    language: 'English',
    format: 'eBook',
    stock: 200,
    isTrending: true,
    tags: ['fiction', 'fantasy', 'adventure'],
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'A masterpiece of science fiction. Epic tale of power, politics, and destiny on an alien world.',
    category: 'Fiction',
    price: 32.00,
    discountedPrice: 24.00,
    rating: 4.7,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 688,
    publicationDate: new Date('1965-06-01'),
    isbn: '978-0441172719',
    language: 'English',
    format: 'eBook',
    stock: 120,
    isFeatured: true,
    tags: ['fiction', 'science-fiction', 'classic'],
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness - understand the psychology behind financial decisions.',
    category: 'Psychology',
    price: 40.00,
    discountedPrice: 30.00,
    rating: 4.8,
    coverImage: 'https://covers.openlibrary.org/b/id/7818879-M.jpg',
    pages: 352,
    publicationDate: new Date('2020-09-08'),
    isbn: '978-0857197689',
    language: 'English',
    format: 'eBook',
    stock: 110,
    isTrending: true,
    tags: ['psychology', 'finance', 'behavior'],
  },
];

const seedDatabase = async () => {
  try {
    await connectDB();
    
    // Clear existing books
    await Book.deleteMany({});
    console.log('Cleared existing books');

    // Insert seed books
    const result = await Book.insertMany(seedBooks);
    console.log(`✅ Seeded ${result.length} books`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
};

seedDatabase();
